# Generated by Django 4.1 on 2022-12-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_booking_bookname_booking_booknumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booknumber',
            field=models.CharField(default='', max_length=12),
        ),
    ]
